server:
  port: 8091
spring:
  output:
    ansi:
      #      enabled: NEVER # 禁用ANSI
      enabled: detect # 是否支持ANSI，是的话多彩输出
  application:
    name: maple
  datasource:
    druid:
      url: jdbc:mysql://39.106.44.72:81/foundation?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: cqf123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 20
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: SELECT 1
      validation-query-timeout: 500
      filters: stat
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.maple.primary.entity # entity的位置
  configuration:
    map-underscore-to-camel-case: true # 驼峰映射到下划线

logging:
  level:
    root: info # 所有包，日志级别为 info
    com.maple.primary.mapper: debug # mybatis 日志为 debug 可输出sql

